# Generated by Django 5.0.2 on 2024-11-29 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='api',
            options={'ordering': ['-created_at'], 'verbose_name': 'API', 'verbose_name_plural': 'APIs'},
        ),
        migrations.AlterModelOptions(
            name='apistatus',
            options={'ordering': ['-checked_at'], 'verbose_name': 'API Status', 'verbose_name_plural': 'API Statuses'},
        ),
        migrations.AlterModelOptions(
            name='feedback',
            options={'ordering': ['-created_at'], 'verbose_name': 'Feedback', 'verbose_name_plural': 'Feedbacks'},
        ),
        migrations.AlterModelOptions(
            name='organization',
            options={'verbose_name': 'Organization', 'verbose_name_plural': 'Organizations'},
        ),
        migrations.AlterModelOptions(
            name='organizationmember',
            options={'verbose_name': 'Organization Member', 'verbose_name_plural': 'Organization Members'},
        ),
    ]
